### ISSUE TITLE
move install commands from scripts to Dockerfile

### ISSUE THREAD

**Issue by ivotron** [popperized/mlperf-workflows#17]
Some benchmarks (e.g. `object_detection`) contain `apt-get` instructions on the scripts they use. We can move these to the `Dockerfile` to avoid having to re-run `apt-get` everytime the workflow runs.

This will also result in having any `install` step in the workflow being removed

**Comment by JayjeetAtGithub** [comment]
Can we put all the install commands in the `Dockerfile` of the `pyyorch/` and `tensorflow/` directories, thus essentially using the same image for all the steps of the workflow ? Or should we create separate `Dockerfile` in the `scripts/` dir for the download and verify steps ?

**Comment by ivotron** [comment]
Yeah, that's OK. that's how IMO dockerfiles should be organized

**Comment by JayjeetAtGithub** [comment]
Sorry, @ivotron. I am a bit confused. So do you mean that we can use the same big image for all the actions?

**Comment by ivotron** [comment]
ideally, each step can use a distinct image, or multiple steps can use the same one, depending on the software being used. For example, if the step that downloads data only uses curl, then we can use a [curl image](https://hub.docker.com/r/byrnedo/alpine-curl/). for that step that verifies the download, a small alpine image can be used, as that only makes use of the `md5sum` utility. For the step that runs the benchmark, if there's already an image in a docker registry that contains the software being used, then we can use that one, otherwise it can build one based on the existing `Dockerfile`.

**Comment by JayjeetAtGithub** [comment]
Got it. Thanks a lot.
