### ISSUE TITLE
make download scripts idempotent

### ISSUE THREAD

**Issue by ivotron** [popperized/mlperf-workflows#19]
For the download step:
 1. obtain the list of files from zip/tar files
 2. compare that with existing files.
 3. skip download if all files are already present

**Comment by JayjeetAtGithub** [comment]
Done for `object_detection` and `single_stage_detector` by [this](https://github.com/popperized/mlperf-workflows/commit/e817e6c3f810033fc38e96f0d955f5fc29611cb8) commit.
